"""
Built-in crop database for Plentica.
Contains common crops with their agronomic and economic properties.
All prices/costs are in generic currency units (e.g., USD, INR) —
adjust market_price_per_ton and costs for your local market.
"""

from plentica.models import Crop, Season, SoilType

# ---------------------------------------------------------------------------
# Crop definitions
# ---------------------------------------------------------------------------

CROPS: list[Crop] = [
    # ── Kharif (monsoon) crops ──────────────────────────────────────────────
    Crop(
        name="Rice",
        water_requirement_mm=1200,
        growing_days=120,
        yield_per_hectare=4.5,
        market_price_per_ton=300,
        fertilizer_cost_per_hectare=150,
        labor_days_per_hectare=40,
        suitable_soils=[SoilType.CLAY, SoilType.CLAY_LOAM, SoilType.SILTY],
        suitable_seasons=[Season.KHARIF],
        min_temperature_c=20,
        max_temperature_c=40,
        seed_cost_per_hectare=50,
    ),
    Crop(
        name="Maize",
        water_requirement_mm=600,
        growing_days=90,
        yield_per_hectare=5.0,
        market_price_per_ton=180,
        fertilizer_cost_per_hectare=120,
        labor_days_per_hectare=25,
        suitable_soils=[SoilType.LOAM, SoilType.SANDY, SoilType.CLAY_LOAM],
        suitable_seasons=[Season.KHARIF, Season.ZAID],
        min_temperature_c=18,
        max_temperature_c=38,
        seed_cost_per_hectare=40,
    ),
    Crop(
        name="Soybean",
        water_requirement_mm=500,
        growing_days=100,
        yield_per_hectare=2.5,
        market_price_per_ton=400,
        fertilizer_cost_per_hectare=80,
        labor_days_per_hectare=20,
        suitable_soils=[SoilType.LOAM, SoilType.CLAY_LOAM],
        suitable_seasons=[Season.KHARIF],
        min_temperature_c=15,
        max_temperature_c=35,
        seed_cost_per_hectare=60,
    ),
    Crop(
        name="Cotton",
        water_requirement_mm=700,
        growing_days=160,
        yield_per_hectare=2.0,
        market_price_per_ton=700,
        fertilizer_cost_per_hectare=200,
        labor_days_per_hectare=50,
        suitable_soils=[SoilType.CLAY, SoilType.CLAY_LOAM, SoilType.LOAM],
        suitable_seasons=[Season.KHARIF],
        min_temperature_c=20,
        max_temperature_c=40,
        seed_cost_per_hectare=80,
    ),
    Crop(
        name="Groundnut",
        water_requirement_mm=400,
        growing_days=120,
        yield_per_hectare=2.0,
        market_price_per_ton=500,
        fertilizer_cost_per_hectare=90,
        labor_days_per_hectare=30,
        suitable_soils=[SoilType.SANDY, SoilType.LOAM],
        suitable_seasons=[Season.KHARIF],
        min_temperature_c=25,
        max_temperature_c=38,
        seed_cost_per_hectare=70,
    ),
    # ── Rabi (winter) crops ─────────────────────────────────────────────────
    Crop(
        name="Wheat",
        water_requirement_mm=400,
        growing_days=120,
        yield_per_hectare=4.0,
        market_price_per_ton=250,
        fertilizer_cost_per_hectare=130,
        labor_days_per_hectare=30,
        suitable_soils=[SoilType.LOAM, SoilType.CLAY_LOAM, SoilType.SILTY],
        suitable_seasons=[Season.RABI],
        min_temperature_c=5,
        max_temperature_c=25,
        seed_cost_per_hectare=45,
    ),
    Crop(
        name="Mustard",
        water_requirement_mm=250,
        growing_days=110,
        yield_per_hectare=1.5,
        market_price_per_ton=550,
        fertilizer_cost_per_hectare=80,
        labor_days_per_hectare=18,
        suitable_soils=[SoilType.LOAM, SoilType.SANDY, SoilType.CLAY_LOAM],
        suitable_seasons=[Season.RABI],
        min_temperature_c=5,
        max_temperature_c=25,
        seed_cost_per_hectare=20,
    ),
    Crop(
        name="Chickpea",
        water_requirement_mm=300,
        growing_days=100,
        yield_per_hectare=1.8,
        market_price_per_ton=600,
        fertilizer_cost_per_hectare=60,
        labor_days_per_hectare=20,
        suitable_soils=[SoilType.LOAM, SoilType.SANDY, SoilType.CLAY_LOAM],
        suitable_seasons=[Season.RABI],
        min_temperature_c=5,
        max_temperature_c=30,
        seed_cost_per_hectare=55,
    ),
    Crop(
        name="Sunflower",
        water_requirement_mm=450,
        growing_days=95,
        yield_per_hectare=1.8,
        market_price_per_ton=480,
        fertilizer_cost_per_hectare=100,
        labor_days_per_hectare=22,
        suitable_soils=[SoilType.LOAM, SoilType.CLAY_LOAM],
        suitable_seasons=[Season.RABI, Season.KHARIF],
        min_temperature_c=10,
        max_temperature_c=35,
        seed_cost_per_hectare=35,
    ),
    # ── Zaid / year-round crops ─────────────────────────────────────────────
    Crop(
        name="Vegetables (mixed)",
        water_requirement_mm=350,
        growing_days=60,
        yield_per_hectare=12.0,
        market_price_per_ton=200,
        fertilizer_cost_per_hectare=200,
        labor_days_per_hectare=60,
        suitable_soils=[SoilType.LOAM, SoilType.CLAY_LOAM, SoilType.SILTY],
        suitable_seasons=[Season.ZAID, Season.KHARIF, Season.RABI],
        min_temperature_c=10,
        max_temperature_c=38,
        seed_cost_per_hectare=100,
    ),
    Crop(
        name="Sugarcane",
        water_requirement_mm=1500,
        growing_days=365,
        yield_per_hectare=70.0,
        market_price_per_ton=35,
        fertilizer_cost_per_hectare=300,
        labor_days_per_hectare=80,
        suitable_soils=[SoilType.LOAM, SoilType.CLAY_LOAM, SoilType.CLAY],
        suitable_seasons=[Season.YEAR_ROUND],
        min_temperature_c=20,
        max_temperature_c=40,
        seed_cost_per_hectare=120,
    ),
    Crop(
        name="Tomato",
        water_requirement_mm=400,
        growing_days=75,
        yield_per_hectare=25.0,
        market_price_per_ton=150,
        fertilizer_cost_per_hectare=250,
        labor_days_per_hectare=70,
        suitable_soils=[SoilType.LOAM, SoilType.SANDY, SoilType.CLAY_LOAM],
        suitable_seasons=[Season.RABI, Season.ZAID],
        min_temperature_c=15,
        max_temperature_c=35,
        seed_cost_per_hectare=90,
    ),
]

# Convenient lookup by name
CROP_BY_NAME: dict[str, Crop] = {c.name: c for c in CROPS}
